name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: '1.15'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ./server
      run: go get

    - name: Build
      working-directory: ./server
      run: go build -v .

    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: server
        path: ./server
    
    #- name: Upload to prod
    #  uses: appleboy/scp-action@master
    #  with:
    #    host: ${{ secrets.HOST }}
    #    username: ${{ secrets.USERNAME }}
    #    #password: ${{ secrets.PASSWORD }}
    #    KEY: ${{ secrets.KEY }}
    #    port: ${{ secrets.PORT }}
    #    rm: true
    #    source: ./server/server
    #    target: "/home/pavel"
    
